add_newline = true

[character]
format = "ğŸ‘‰ "

[directory]
truncation_length = 5
truncate_to_repo = false

[aws]
style = "bold blue"
symbol = "@ "

[aws.region_aliases]
ap-northease-1 = "jp"

[git_branch]
symbol = "ğŸª´  "

[git_status]
conflicted = "ğŸ¥"
ahead = "ğŸšš"
behind = "ğŸ½"
diverged = "ğŸ›"
untracked = "ğŸŒ¾"
stashed = "ğŸ¥¡"
modified = "ğŸš"
staged = 'ğŸ™'
renamed = "ğŸ¶"
deleted = "ğŸ‘…"

[nodejs]
symbol = "â¬¢ "

